apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fleetman.fullname" . }}-api-gateway
spec:
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
   {{- end }} 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fleetman.fullname" . }}-api-gateway