apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleetman.fullname" . }}-queue
  labels:
    {{- include "fleetman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.queue.service.type }}
  ports:
    - port: {{ .Values.queue.service.port }}
      targetPort: admin-console
      protocol: TCP
      name: admin-console
      nodePort: {{ .Values.queue.service.nodePort }}

    - port: {{ .Values.queue.service.portEndpoint }}
      targetPort: endpoint
      protocol: TCP
      name: endpoint

  selector:
    {{- include "fleetman.selectorLabels" . | nindent 4 }}
